#!/bin/bash
#
# Call gensparseg for all n in a range.
#
# Arguments:
#   The range of n as arguments to pass to seq.
#   Arguments to pass to gensparseg.
#
# Examples:
#   Count the number of Laman graphs for n in the range [1, 10].
#   ./geng_range 10 -K2 -u
#
#   Count the number of Laman graphs for n in the range [5, 10].
#   ./geng_range "5 10" -K2 -u
#
#   Count the number of Laman graphs for even n in the range [2, 10].
#   ./geng_range "2 2 10" -K2 -u

ns=${1:?"Please specify a sequence of n"}

for i in $(seq $ns)
do
    ./gensparseg $i "${@:2}"
done
